const fs = require('fs-extra')
const os = require('os')
const exec = require('child_process').execSync
// const genIcons = require('./genIcons.js')
fs.emptyDirSync('../TEMP')
fs.copySync('.','../TEMP')
// console.log(exec('node-prune ../TEMP').toString())
// genIcons()
if (os.platform() === 'win32') require('./prepMake-Win')('../TEMP/')
else if (os.platform() === 'darwin') require('./prepMake-Mac')('../TEMP/')